-- MySQL Script generated by MySQL Workbench
-- 04/06/16 13:04:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema springtutorial
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `springtutorial` ;

-- -----------------------------------------------------
-- Schema springtutorial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `springtutorial` DEFAULT CHARACTER SET utf8 ;
USE `springtutorial` ;

-- -----------------------------------------------------
-- Table `springtutorial`.`authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `springtutorial`.`authorities` ;

CREATE TABLE IF NOT EXISTS `springtutorial`.`authorities` (
  `username` VARCHAR(60) NOT NULL,
  `authority` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `springtutorial`.`offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `springtutorial`.`offers` ;

CREATE TABLE IF NOT EXISTS `springtutorial`.`offers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `springtutorial`.`rentallocations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `springtutorial`.`rentallocations` ;

CREATE TABLE IF NOT EXISTS `springtutorial`.`rentallocations` (
  `address1` VARCHAR(75) NULL DEFAULT NULL,
  `address2` VARCHAR(75) NULL DEFAULT NULL,
  `city` VARCHAR(30) NULL DEFAULT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `rentalLocationId` INT(11) NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(25) NULL DEFAULT NULL,
  `postalcode` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`rentalLocationId`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `springtutorial`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `springtutorial`.`users` ;

CREATE TABLE IF NOT EXISTS `springtutorial`.`users` (
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(80) NULL DEFAULT NULL,
  `enabled` TINYINT(1) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use springtutorial;

insert into authorities (username, authority) values ("johnwpurcell","ROLE_USER");
insert into authorities (username, authority) values ("Administrator","ROLE_ADMIN");

insert into users (username, password, enabled, email) values ("johnwpurcell","hello", 1, "john@caveofprogramming.com");
insert into users (username, password, enabled, email) values ("Administrator", "hellohello", 1, "admin@caveofprogramming.com");

insert into offers (name, email, text) values ("John Purcell", "johnwpurcell@caveofprogramming.com", "I will write beautiful java code for you");
